### ISSUE TITLE
Additional maintainer

### ISSUE THREAD

**Issue by andresv** [stm32-rs/stm32g0xx-hal#10]
I have big plans with this crate as I am using G0 in production.
Basically my plan is to port drivers from [stm32l0xx-hal](https://github.com/stm32-rs/stm32l0xx-hal/tree/master/src) after we have tackled `DMAMUX`: #12.
Also CI must be setup. There are lot of stm32 HALs that are using it, we can do the same.

So I would like to become a co-maintainer of this crate. Let me know what do you think.

**Comment by dotcypress** [comment]
I think it is great! 
I'll send you an invite.

**Comment by andresv** [comment]
Super! I am now also maintainer.
