### ISSUE TITLE
i2c embedded-hal

### ISSUE THREAD

**Issue by morteza-norouzi** [stm32-rs/stm32g0xx-hal#150]
I would like to know How can I use embedded-hal trait for i2c object of this crate? (ssd1306 crate needs this trait to work) (embedded_graphics too)

**Comment by andresv** [comment]
I recommend to use actively maintained embassy-stm32 HAL: https://github.com/embassy-rs/embassy/tree/main/embassy-stm32.

**Comment by andresv** [comment]
This crate uses old embedded-hal 0.2.6. It should be updated to stable 1.0 which is now used by most of the sensor drivers.
