### ISSUE TITLE
Version 0.1.0

### ISSUE THREAD

**Issue by andresv** [stm32-rs/stm32g0xx-hal#52]
@dotcypress we have got bunch of good PRs lately, lets publish a new version to crates.io.
I think we could name it `0.1.0`. Minor version number bump looks more solid than just using bugfix.

Lets also tag upcoming crates.io versions here. Then it is good to see what 0.1.0 contains and what is changed after that.

**Comment by dotcypress** [comment]
Yup, totally make sense, will do it today!

**Comment by dotcypress** [comment]
Done!
