### ISSUE TITLE
Build fails with --features stm32g081

### ISSUE THREAD

**Issue by andresv** [stm32-rs/stm32g0xx-hal#6]
`cargo build --example blinky --features stm32g081`

```
error: symbol `DEVICE_PERIPHERALS` is already defined
    --> /Users/andres/.cargo/registry/src/github.com-1ecc6299db9ec823/stm32g0-0.10.0/src/stm32g081/mod.rs:1160:1
     |
1160 | static mut DEVICE_PERIPHERALS: bool = false;
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `stm32g0`.

To learn more, run the command again with --verbose.
```

**Comment by andresv** [comment]
I compared `stm32g07x` and `stm32g081` dirs from here https://github.com/stm32-rs/stm32-rs-nightlies and they were exactly the same.

I also used this `stm32-rs-nightlies` to build examples, so `stm32g0xx-hal/Cargo.toml` was modified to:
```
#stm32g0 = "0.10.0"
stm32g0 = {git = "https://github.com/stm32-rs/stm32-rs-nightlies"}
```

**Comment by andresv** [comment]
Ahaa, `default` is not working as expected. When I replaced `default = ["rt", "stm32g07x"]` with `default = ["rt", "stm32g081"]`. I was able to build blink with `cargo build --example blinky --features stm32g081`.

```
[features]
#default = ["rt", "stm32g07x"]
default = ["rt", "stm32g081"]
rt = ["stm32g0/rt"]
stm32g07x = ["stm32g0/stm32g07x"]
stm32g030 = ["stm32g0/stm32g030"]
stm32g031 = ["stm32g0/stm32g031"]
stm32g041 = ["stm32g0/stm32g041"]
stm32g081 = ["stm32g0/stm32g081"]
```

**Comment by emilhoeiriis** [comment]
Issue persists

**Comment by andresv** [comment]
This is now fixed. However now actual MCU must be specified to build examples `cargo build --example blinky --features stm32g081`.
