### ISSUE TITLE
Configuring I2C pins causes them to be temporarily pulled low

### ISSUE THREAD

**Issue by davidlattimore** [stm32-rs/stm32g0xx-hal#87]
Currently SDAPin and SCLPin are only implemented for pins in mode Output<OpenDrain>. Configuring the pins as open-drain prior to them being reconfigured for their alternate function results in the pins momentarily being pulled low (see scope trace below). I've found that this can confuse other devices on the bus. In my application, I'm currently working around this by using core::mem::transmute to construct a pin that thinks it's configured as open-drain, when it is in fact still in its default state. This seems to work well, but is pretty ugly.

Would you be open to implementing SDAPin and SCLPin for the pins in their default state? If so, I'm happy to send a pull request. Would you prefer that I implement for both DefaultMode and Output<OpenDrain> or just DefaultMode? Removing the implementations for Output<OpenDrain> would be a breaking change.

![DS1Z_QuickPrint7](https://user-images.githubusercontent.com/8983542/140987798-8015138d-0e36-4832-9b17-7348e6ad57fd.png)

**Comment by andresv** [comment]
@dotcypress do you have any thoughts about this?

**Comment by dotcypress** [comment]
@davidlattimore Good catch!
I think we can implement SDAPin/SCLPin for pins in default mode.

I can try to do that on a weekend, but if you have something already - I will be happy to review.
